### ISSUE TITLE
[v16.0.0]Secret "sentry-sentry-secret" not found

### ISSUE THREAD

**Issue by throrin19** [sentry-kubernetes/charts#742] opened 2022-10-04 08:38 UTC
After upgrade from 15.x to 16.x, 

I have this error in sentry-cron, sentry-web, sentry-worker : 

```
CreateContainerConfigError (secret "sentry-sentry-secret" not found)
```

I did not set `sentry.existingSecret` and `sentry.existingSecretKey`.

Normally, the chart must create the secret.

**Comment by amakarov70** [comment] 2022-10-04 16:41
@throrin19  Try to comment Line 15 in hooks/sentry-secret-create.yaml

**Comment by echel0n** [comment] 2022-10-06 04:12
I am having the same issue with v16.0.1 as well

**Comment by Mokto** [comment] 2022-10-06 05:36
Have you tried @amakarov70's comment ? I can create an hotfix quickly if this is a confirmed fix (seems plausible). I personally didn't have any issue with it.

**Comment by atalakey4work** [comment] 2022-10-06 07:01
@Mokto I have tried it and it indeed fixes the issue.

Adding a delete policy on a secret doesn't make sense to me but kindly keep in mind that this change was introduced 3 days ago during the upgrade to v16 and it seems that it was done for a reason.

**Comment by atalakey4work** [comment] 2022-10-06 07:07
Oh and FYI the issue only happens when ".Values.hooks.removeOnSuccess" is set to "true".

You can just replace: "{{ if .Values.hooks.removeOnSuccess }}hook-succeeded,{{ end }}before-hook-creation"
To: "helm.sh/hook-delete-policy": "before-hook-creation"

The secret should always be present and should not be deleted upon successful load. Seems that it was a classic copy/past mistake.

**Comment by amakarov70** [comment] 2022-10-06 08:50
@Mokto https://github.com/sentry-kubernetes/charts/issues/742#issuecomment-1269454861 . i just offered a quick solution

**Comment by Mokto** [comment] 2022-10-06 10:55
Seems that it was a classic copy/past mistake => Agreed

**Comment by Mokto** [comment] 2022-10-06 12:58
Merged.

16.0.2 should be available in a few minutes.

**Closed as completed** 2022-10-06 12:58 UTC

**Comment by Yomanz** [comment] 2022-10-09 14:40
@Mokto Am I going to be able to recreate the secret or is my instance  broken now because I don't have the original key that was in that file?

**Comment by throrin19** [comment] 2022-10-10 11:57
@Yomanz In my case I create the secret after the error in 16.0.0 and I have no problem. The sentry-key is only used for session if i correctly understand

**Comment by Yomanz** [comment] 2022-10-11 14:48
> @Yomanz In my case I create the secret after the error in 16.0.0 and I have no problem. The sentry-key is only used for session if i correctly understand

Thanks for confirming :)
