### ISSUE TITLE
Source maps not working after upgrades.

### ISSUE THREAD

**Issue by Scong** [sentry-kubernetes/charts#529] opened 2021-12-02 04:53 UTC
I believe the config prevents source maps from working as it uses the default cache rather than Redis or such? With the default cache being the dummy cache.

I think the person who wrote this https://engblog.yext.com/post/sentry-js-source-maps was running into the same issue. They go into more detail on this as well.

![image](https://user-images.githubusercontent.com/4022295/144359035-d99b006c-aa91-4d4b-9008-321a26609718.png)

https://github.com/sentry-kubernetes/charts/blob/bf8fdd596861a22bff74299f9d23b60644d7a08f/sentry/templates/configmap-sentry.yaml

It looks to me like django cache is required for source maps? I'm confused how this could be considered optional? How are other peoples source maps working? 

```
# Sentry currently utilizes two separate mechanisms. While CACHES is not a
  # requirement, it will optimize several high throughput patterns.
  # CACHES = {
  #     "default": {
  #         "BACKEND": "django.core.cache.backends.memcached.MemcachedCache",
  #         "LOCATION": ["memcached:11211"],
  #         "TIMEOUT": 3600,
  #     }
  # }
  ```
 
(Source maps are not too large in my case< 10MB)
![image](https://user-images.githubusercontent.com/4022295/144360591-ca945d84-6ba9-4834-80a7-7d68b6f25f81.png)

Chart version 11.9

Sentry version 21.9.0

**Comment by Scong** [comment] 2021-12-02 05:50
I ended up spinning up a memcached and adding config value for sentryConfPy.
Feels weird to have to do it though. 
```
config: 
      sentryConfPy: |
        CACHES = {
          "default": {
              "BACKEND": "django.core.cache.backends.memcached.MemcachedCache",
              "LOCATION": ["memcached:11211"],
              "TIMEOUT": 3600,
          }
        }
        import memcache
        memcache.SERVER_MAX_VALUE_LENGTH = 1024 * 1024 * 25
```

This didn't seem to solve my issue though. Hmm. Still verifying, may need to wait for new events.

**Comment by DreamWenzhe** [comment] 2021-12-16 15:11
So, what happened in the end?

**Comment by Scong** [comment] 2022-02-07 17:28
@[DreamWenzhe](https://github.com/DreamWenzhe)

Spinning up a mem cache worked, and updating the config. There are some other sourcemap issues but I believe those are all related to sourcemap delivery. Most of our apps I can now view sourcemaps for. 

I consider this still an issue in the default behavior of the chart / Sentry image? But I don't see very many people complaining about it, so not sure?

**Comment by Mokto** [comment] 2022-04-05 02:45
This issue is stale because it has been open for 30 days with no activity.

**Comment by z0rc** [comment] 2022-04-05 08:52
@Mokto the issue still stands. Helm chart installation still missing memcache service and relevant configuration.

**Comment by Prajna** [comment] 2022-04-16 12:21
I can confirm that CACHES is not optional for source maps.

I believe this is a bug, but I am not sure why nobody is complaining about it?

**Comment by jnm** [comment] 2022-04-27 02:52
> I believe this is a bug, but I am not sure why nobody is complaining about it?

Here, I'll complain :stuck_out_tongue_winking_eye:

Mine is almost surely a bad approach, but to get source maps working quickly on my fairly-low-traffic instance, I used [`django.core.cache.backends.db.DatabaseCache`](https://docs.djangoproject.com/en/2.2/topics/cache/#database-caching-1) by adding the following to my `values.yaml`:
```
config:
  sentryConfPy: |
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
            'LOCATION': 'ugly_cache_table_sorry',
        }
    }
```
This requires running the Django `createcachetable` management command, e.g. by:
1. `kubectl -n sentry exec -it svc/sentry-web -- bash`
1. You'll see lots of `django.db.utils.ProgrammingError: UndefinedTable('relation "ugly_cache_table_sorry" does not exist\nLINE 1: SELECT "cache_key", "value", "expires" FROM "ugly_cache_tabl...`
1. Keep your fortitude; ignore them, and execute `sentry django createcachetable`
1. Enjoy source maps

…or better yet, use memcached [as mentioned above](https://github.com/sentry-kubernetes/charts/issues/529#issuecomment-984314516).

**Comment by Mokto** [comment] 2022-05-27 03:17
This issue is stale because it has been open for 30 days with no activity.

**Comment by z0rc** [comment] 2022-05-27 08:56
Not stale.

**Comment by Mokto** [comment] 2022-06-27 03:33
This issue is stale because it has been open for 30 days with no activity.

**Comment by z0rc** [comment] 2022-06-27 08:52
Still relevant.

**Comment by kong62** [comment] 2022-07-15 01:57
Not stale.

**Comment by andymcblane** [comment] 2022-08-01 07:14
Same issue here

**Comment by z0rc** [comment] 2022-08-01 10:18
Fixed with https://github.com/sentry-kubernetes/charts/pull/667.

**Closed as completed** 2022-08-01 10:43 UTC
