### ISSUE TITLE
Events are missing

### ISSUE THREAD

**Issue by sagor999** [sentry-kubernetes/charts#68] opened 2020-05-19 16:59 UTC
Hi,
wondering if anyone encountered similar issue and might know what might be causing this.
Sentry receives event, sends email about event being created. But, if you follow the link to sentry, it says:
`Sorry, the events for this issue could not be found.`
Even though it shows: 
`Events: 1`
but if you click on `Events` tab, it is also empty.

It happens to some events only. At some point something changes, and then events are coming through and showing up just fine.

Nothing in logs shows any errors or anything that would explain this. 
snuba consumer is working fine and no errors.
workers are working fine and not backlogged. 
Queue is completely empty.

Only thing that is different from default chart, is that we don't use rabbitmq, instead using redis as broker. Could that cause such behavior? 

Any help or ideas would be greatly appreciated.

**Comment by Mokto** [comment] 2020-05-19 17:29
Thanks for your report.

Actually I've seen the same behaviour (rarely) and I'm using RabbitMQ. I've been unable to pinpoint why this is the case.

**Comment by J0sh0nat0r** [comment] 2020-05-19 18:42
We encountered a similar issue and discovered it was to do with how Snuba / Clickhouse are configured. By default it's configured in a local dataset mode and this chart deploys 3 Clickhouse replicas which don't seem to replicate data (maybe intended or due to the lack of Zookeeper?) the fix was to configure Snuba to use distributed dataset mode and create a distributed table named `sentry_dist` on every Clickhouse replica pointing to the `sentry_local` table. I think this chart may need to support deploying Zookeeper along with Clickhouse to get everything running smoothly and I intend to open a pull request when I get everything figured out. For now you can take a look at my fork [here](https://github.com/J0sh0nat0r/sentry-kubernetes-charts) to see what I've changed so far, for now it is working smoothly. The only chart values required should be:
```yaml
snuba:
  migrateJob:
    env:
      - name: DATASET_MODE
        value: local
config:
  snubaSettingsPy: |
    DATASET_MODE = env("DATASET_MODE", "distributed")
```
To connect to a Clickhouse node (from a shell on one):
```
clickhouse-client -h sentry-sentry-clickhouse-0
```
The query to create the distributed table (must currently be run on all nodes, may be fixed with Zookeeper? I'm not experienced with Clickhouse):
```sql
CREATE TABLE default.sentry_dist AS default.sentry_local ENGINE = Distributed(sentry-sentry-clickhouse, default, sentry_local, rand())
```
Substite `sentry-sentry` for your release name.
I apologise for how poorly written this response is, I'm still experimenting with this.

**Comment by sagor999** [comment] 2020-05-19 18:45
@J0sh0nat0r oh interesting! quick question: you are saying that this chart doesn't deploy zookeeper, but it actually does deploy zookeeper. At least I definitely see it running.

**Comment by J0sh0nat0r** [comment] 2020-05-19 18:54
@sagor999 I think the instance of Zookeeper this chart deploys is used for Kafka, maybe it could also be utilized by Clickhouse though?

EDIT: Checking the Clickhouse config it doesn't seem to use it currently

**Comment by Mokto** [comment] 2020-05-20 06:32
@J0sh0nat0r amazing findings ! 

Really smart.

I guess we could include this CREATE TABLE inside the chart as a hook, as some point.

**Comment by sagor999** [comment] 2020-05-20 18:31
@J0sh0nat0r I will give it a try today. Will let you know how it works.
Did notice a minor bug in your chart.
In `snuba-migrate-job.job.yaml` and in `snuba-db-init.job.yaml` this line:
`{{ toYaml .Values.snuba.migrateJob.env | indent 8 }}`
indent has to be 10. otherwise helm fails with errors. 
so correct line is:
`{{ toYaml .Values.snuba.migrateJob.env | indent 10 }}`

**Comment by sagor999** [comment] 2020-05-20 18:45
@J0sh0nat0r 
Having an issue with clickhouse, maybe you can help out.
I created sentry_local table on all 3 clickhouse nodes.
But, snuba consumer crashes with:
```
snuba.clickhouse.errors.ClickhouseError: [60] Received from sentry-clickhouse-replica-1.sentry-clickhouse-replica-headless.ctla.svc.cluster.local:9000. DB::Exception: Table default.sentry_local doesn't exist.. (version 19.16.19.85 (official build))    
```

So I tried to create that table on a replica as well, but getting this:
```
sentry-clickhouse :) CREATE TABLE default.sentry_dist AS default.sentry_local ENGINE = Distributed(sentry-clickhouse, default, sentry_local, rand())

CREATE TABLE default.sentry_dist AS default.sentry_local
ENGINE = Distributed(sentry - clickhouse, default, sentry_local, rand())

Received exception from server (version 19.16.19):
Code: 60. DB::Exception: Received from sentry-clickhouse-replica-0:9000. DB::Exception: Table default.sentry_local doesn't exist.. 
```

Maybe you have some ideas how to resolve this?

Thank you!

**Comment by J0sh0nat0r** [comment] 2020-05-20 19:14
@sagor999 Good catch with the env, thanks :)
Unfortunately it seems I was wrong about Zookeeper and even with it enabled it's still required to create the tables on each node individually, so we'll probably need to update the job to do that.
As for the error you're facing: Currently the `snuba migrate` command is only run on the main Clickhouse nodes, you should be able to exec into a Snuba node and run the following:
```bash
export SNUBA_SETTINGS="docker"
export DEFAULT_BROKERS="sentry-sentry-kafka:9092"
export CLICKHOUSE_PORT="9000"

# Repeat for each Clickhouse node
export CLICKHOUSE_HOST="sentry-sentry-clickhouse-0.sentry-sentry-clickhouse-headless"
snuba bootstrap --force
snuba migrate
export CLICKHOUSE_HOST="sentry-sentry-clickhouse-replica-0.sentry-sentry-clickhouse-replica-headless"
snuba bootstrap --force
snuba migrate
```
After that you should have the `sentry_local` table available on all Clickhouse nodes

EDIT: Fix replica host
EDIT 2: Add bootstrap command

**Comment by sagor999** [comment] 2020-05-20 19:20
@J0sh0nat0r ah, I see.
Hm, snuba migrate is tripping now on replica:
`export CLICKHOUSE_HOST="sentry-clickhouse-replica-0.sentry-clickhouse-replica-headless"`
Error:
```
2020-05-20 19:19:01,788 Migrating dataset events_migration
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 11, in <module>
    load_entry_point('snuba', 'console_scripts', 'snuba')()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/migrate.py", line 41, in migrate
    run(clickhouse, dataset)
  File "/usr/src/snuba/snuba/migrations/migrate.py", line 48, in run
    _run_schema(conn, schema)
  File "/usr/src/snuba/snuba/migrations/migrate.py", line 20, in _run_schema
    local_schema = get_local_schema(conn, clickhouse_table)
  File "/usr/src/snuba/snuba/migrations/parse_schema.py", line 164, in get_local_schema
    for cols in conn.execute("DESCRIBE TABLE %s" % table_name)
  File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/client.py", line 214, in execute
    columnar=columnar
  File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/client.py", line 334, in process_ordinary_query
    columnar=columnar)
  File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/client.py", line 83, in receive_result
    return result.get_result()
  File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/result.py", line 48, in get_result
    for packet in self.packet_generator:
  File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/client.py", line 95, in packet_generator
    packet = self.receive_packet()
  File "/usr/local/lib/python3.7/site-packages/clickhouse_driver/client.py", line 112, in receive_packet
    raise packet.exception
clickhouse_driver.errors.ServerException: Code: 60.
DB::Exception: Table default.errors_local doesn't exist.. Stack trace:

0. 0x559c7fc41544 StackTrace::StackTrace() /usr/bin/clickhouse
1. 0x559c82f5852e DB::Context::getTableImpl(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DB::Exception*) const /usr/bin/clickhouse
2. 0x559c82f58755 DB::Context::getTable(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const /usr/bin/clickhouse
3. 0x559c8374f697 DB::InterpreterDescribeQuery::executeImpl() /usr/bin/clickhouse
4. 0x559c8374fb1e DB::InterpreterDescribeQuery::execute() /usr/bin/clickhouse
5. 0x559c830f6936 ? /usr/bin/clickhouse
6. 0x559c830f7bb2 DB::executeQuery(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool, bool) /usr/bin/clickhouse
7. 0x559c7fccd504 DB::TCPHandler::runImpl() /usr/bin/clickhouse
8. 0x559c7fccdfff DB::TCPHandler::run() /usr/bin/clickhouse
9. 0x559c83c75064 Poco::Net::TCPServerConnection::start() /usr/bin/clickhouse
10. 0x559c83c757c1 Poco::Net::TCPServerDispatcher::run() /usr/bin/clickhouse
11. 0x559c841edbc9 Poco::PooledThread::run() /usr/bin/clickhouse
12. 0x559c841eb7d0 Poco::ThreadImpl::runnableEntry(void*) /usr/bin/clickhouse
13. 0x559c8497d5c4 ? /usr/bin/clickhouse
14. 0x7fb942c216db start_thread /lib/x86_64-linux-gnu/libpthread-2.27.so
15. 0x7fb94274688f __clone /lib/x86_64-linux-gnu/libc-2.27.so
```

Would appreciate help with that error.

**Comment by sagor999** [comment] 2020-05-20 19:24
nvm, figured it out.
Had to run this command for each replica before running migrate:
`snuba bootstrap --force`

**Comment by sagor999** [comment] 2020-05-20 19:25
Snuba replacer is now working. Thank you for help, @J0sh0nat0r !
Hopefully this will fix missing events now.

**Comment by J0sh0nat0r** [comment] 2020-05-20 19:28
@sagor999 Ah, for some reason I didn't have to run that but glad to hear replacer's working now. Keep me posted as to how it goes ;) Happy to help!

**Comment by sagor999** [comment] 2020-05-20 19:44
One quick note: all those random missing events are now all back in sentry. So it is definitely working. Was not expecting that sentry would be able to recover those, so was pleasantly surprised.

**Comment by J0sh0nat0r** [comment] 2020-05-21 18:08
PR opened :)

**Comment by Mokto** [comment] 2020-05-22 07:42
Thanks again @J0sh0nat0r. That was a difficult one.

**Comment by Mokto** [comment] 2020-05-25 08:34
Guys have you tried the new version ?
I seem to still have some not found events.

Thanks.

**Comment by sagor999** [comment] 2020-05-25 13:30
@Mokto I have not tried your version yet. But I have been using @J0sh0nat0r 's and so far no missing events on my end. I am getting about 5-10k events a day. 

Do you have those missing events from after the switch or before the switch? I noticed that not all of my missing events were recovered after the switch, but I am not seeing any new not found events.

**Comment by Mokto** [comment] 2020-05-25 14:03
Thanks.

To be sure I removed all my issues from Sentry. And now all of the new one don't have have events associated.

The thing is that I see them without any issue here :
/organizations/ocean/events/

**Comment by sagor999** [comment] 2020-05-25 14:07
Yeah, I don't seem to have that issue.
I am wondering if some step is missing. I did not look through PR yet to verify there are no missing steps. 
Have you checked logs for snuba pods? is there anything there complaining by any chance?

**Comment by Mokto** [comment] 2020-05-25 15:31
Nothing in snuba, only some 404 in #internal sentry.

I'll start from scratch tomorrow morning!

**Comment by J0sh0nat0r** [comment] 2020-05-25 16:47
@Mokto I switched our production setup over to the main chart and haven't encountered this, would you mind sharing your values / release name so I can try to reproduce locally?

**Comment by Mokto** [comment] 2020-05-26 08:51
I've just tried removing everything (except postgres/redis/rabbitmq, which are external charts) and deploy it with argoCD.

I never see events anymore.
I mean, I do see events here:

<img width="1096" alt="Screenshot 2020-05-26 at 10 33 57" src="https://user-images.githubusercontent.com/5103928/82878924-7d769900-9f3c-11ea-9f9a-64332af18907.png">

But whenever I click on any on those events, I get a not found error.

Here is my chart config (release name is sentry):

```
  user:
    create: false

  hooks:
    enabled: true

  system:
    url: 'https://xxxxxx'
    adminEmail: 'support@xxxx.io'
    secretKey: 'xxxx'
    public: false
  
  github:
    appId: "xxxxx"
    appName: xxxxx
    clientId: "Iv1.xxxxx"
    clientSecret: "xxxxxx"
    privateKey: "xxxxx"
    webhookSecret: "xxxxx"
  

  githubSso:
    clientId: "xxxxxx"
    clientSecret: "xxxxxxx"

  slack:
    clientId: "xxxxxx"
    clientSecret: "xxxxxx"
    verificationToken: "xxxxxx"

  mail:
    backend: smtp # smtp
    useTls: true
    username: sentry@xxxxx
    password: xxxxxx
    port: 587
    host: smtp.eu.mailgun.org
    from: noreply@xxxxx.io

  auth:
    register: false

  postgresql:
    enabled: false
    postgresqlHost: postgres-sentry.xxxxx
    postgresqlPort: 5432
    postgresqlUsername: postgres
    postgresqlPassword: xxxxxxxx
    postgresqlDatabase: sentry
    postgresSslMode: require
  
  redis:
    enabled: false
    host: redis-sentry.xxxx
    password: xxxxx

  service:
    type: ClusterIP

  sentry:
    web:
      replicas: 3
      resources:
        limits:
          cpu: 2000m
          memory: 1Gi
        requests:
          cpu: 700m
          memory: 512Mi
      nodeSelector: {}
      # tolerations: []
      # podLabels: []

      autoscaling:
        enabled: true
        minReplicas: 3
        maxReplicas: 30
        targetCPUUtilizationPercentage: 70

    worker:
      replicas: 3
      resources:
        limits:
          cpu: 2000m
          memory: 1Gi
        requests:
          cpu: 350m
          memory: 512Mi
      nodeSelector: {}

    cron:
      replicas: 1
      resources:
        limits:
          cpu: 2000m
          memory: 1Gi
        requests:
          cpu: 350m
          memory: 512Mi
      nodeSelector: {}

  snuba:
    api:
      replicas: 3
      resources:
        limits:
          cpu: 2000m
          memory: 1Gi
        requests:
          cpu: 350m
          memory: 1Gi
      nodeSelector: {}

      autoscaling:
        enabled: true
        minReplicas: 3
        maxReplicas: 15
        targetCPUUtilizationPercentage: 70

    consumer:
      replicas: 3

  rabbitmq:
    enabled: false
    host: rabbitmq-tcp-sentry.xxxx
    rabbitmqUsername: root
    rabbitmqPassword: xxxxx

  filestore:
    backend: gcs
    gcs:
      credentialsFile: credentials.json
      secretName: sentry-gcs
      bucketName: xxxx-sentry
    
    filesystem:
      persistence:
        enabled: false

  kafka:
    enabled: true
    metrics:
      kafka:
        enabled: true
      serviceMonitor:
        enabled: true

  clickhouse:
    clickhouse:
      persistentVolumeClaim:
        enabled: true
        dataPersistentVolume: 
          enabled: true
          accessModes: 
          - "ReadWriteOnce"
          storageClassName: "standard"
          storage: "30Gi"

```

Weirdly, when I go to that Not found page, snuba api is logging this :
```
POST /query HTTP/1.1" 200 338 "eventstore.get_event_by_id_nodestore"
```

But Sentry-web is logging this:

```
[WARNING] sentry.eventstore.snuba.backend: eventstore.missing-snuba-event (event_id=u'dde17b3738b940dcbb7915da4127c538' project_id=1L)
08:50:51 [WARNING] django.request: Not Found: /organizations/ocean/projects/internal/events/dde17b3738b940dcbb7915da4127c538/ (status_code=404 request=<WSGIRequest: GET u'/organizations/ocean/projects/internal/events/dde17b3738b940dcbb7915da4127c538/'>)
10.48.2.12 - - [26/May/2020:08:50:50 +0000] "GET /organizations/ocean/projects/internal/events/dde17b3738b940dcbb7915da4127c538/ HTTP/1.1" 404 7070 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
```

Thanks!

**Comment by sagor999** [comment] 2020-05-26 14:06
Hm. Did your snuba migrate job completed fine?
I noticed in [snuba-migrate.job.yaml](https://github.com/sentry-kubernetes/charts/blob/5a14b8b59c786eaa352c521dea00feb765cc2dc1/sentry/templates/hooks/snuba-migrate.job.yaml#L50) when we call `snuba migrate` we don't execute `snuba bootstrap --force` first. I know that in my case if was tripping and not doing migrate because of that. Could have similar happened to you?

**Comment by Mokto** [comment] 2020-05-26 14:26
Yeah, everything went fine, I just checked the logs.
And jobs are executed in the right order, thanks to "helm.sh/hook-weight".

**Comment by Mokto** [comment] 2020-05-27 04:56
I just tried running a new standalone version of sentry with that command:

```
helm upgrade sentrytest sentry/sentry --set postgresql.postgresqlPassword=abcdefgh -n sentrytest --install
```

Same issue.

I'll re-open.

**Comment by Mokto** [comment] 2020-05-27 06:30
Ok, I think I found out why, after trying 10 different configurations.

I needed to downgrade sentry & snuba images.

I'm still unsure why but i think it's because they've added some new services here: https://github.com/getsentry/onpremise/blob/master/docker-compose.yml.

Hotfix coming soon.

**Comment by Mokto** [comment] 2020-05-27 06:57
Fixed through 1.3.0

**Closed as completed by Mokto** 2020-05-27 06:57 UTC

**Comment by sagor999** [comment] 2020-05-27 14:33
@Mokto oh good find! Sorry for not being able to help out much.

**Comment by J0sh0nat0r** [comment] 2020-05-28 01:17
@Mokto I don't seem to be seeing this issue in prod, and we're running the latest tags. Could it have since been fixed?

**Comment by Mokto** [comment] 2020-05-28 06:57
When was the "latest" tag pulled for the last time?
Or do you have a pullpolicy to "always"?

**Comment by J0sh0nat0r** [comment] 2020-05-28 13:02
@Mokto Sorry I should've specified, we're running the latest commits as the tags are auto-updated via Flux

**Comment by chipzzz** [comment] 2024-08-02 16:02
@J0sh0nat0r , just discovering distributed clickhouse snuba settings they have changed over time but is 
```
 DATASET_MODE = env("DATASET_MODE", "distributed")
 ```
 still required? Or the updated snuba config sufficient to run with distributed external clickhouse ?
 https://github.com/sentry-kubernetes/charts/blob/develop/charts/sentry/templates/_helper-snuba.tpl
